### ISSUE TITLE
ObjectIterator  BUG

### ISSUE THREAD

**Issue by InertiaKT** [Yaocool/async-oss#3]
asyncio_oss.ObjectIterator 的父类 _BaseIterator 实现了 __aiter__  方法。
__aiter__  是否应该删除def 前的 async ,当有 async 时 会触发
TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: coroutine

**Comment by Yaocool** [comment]
确实存在这个问题，可以提 pr fix 并补充对应的测试用例 @InertiaKT

**Comment by Yaocool** [comment]
已 fix @InertiaKT
