### ISSUE TITLE
put_object_tagging BUG

### ISSUE THREAD

**Issue by InertiaKT** [Yaocool/async-oss#4]
put_object_tagging 会返回 asyncio_oss.exceptions.SignatureDoesNotMatch，但是我不知道该如何解决，麻烦看一下，多谢

**Comment by Yaocool** [comment]
> put_object_tagging 会返回 asyncio_oss.exceptions.SignatureDoesNotMatch，但是我不知道该如何解决，麻烦看一下，多谢

已经复现了，在排查，如果影响使用可使用 `put_object` 接口添加 header 来实现添加 tag 的功能，参考 [https://help.aliyun.com/document_detail/121939.html?spm=a2c4g.121931.0.0.61247df5WoAtni](https://help.aliyun.com/document_detail/121939.html?spm=a2c4g.121931.0.0.61247df5WoAtni)

**Comment by Yaocool** [comment]
> > put_object_tagging 会返回 asyncio_oss.exceptions.SignatureDoesNotMatch，但是我不知道该如何解决，麻烦看一下，多谢
> 
> 已经复现了，在排查，如果影响使用可使用 `put_object` 接口添加 header 来实现添加 tag 的功能，参考 https://help.aliyun.com/document_detail/121939.html?spm=a2c4g.121931.0.0.61247df5WoAtni

already fixed, see [this pull request](https://github.com/Yaocool/async-oss/commit/95e3a99ab9f9ff0f3052f6c4748581438534b66e).  @InertiaKT
